/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package stii.v2.pkg0;

import dbconnection.dbconnect;
import java.awt.Color;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;

/**
 *
 * @author hansaka
 */
public class login extends javax.swing.JFrame {

    /**
     * Creates new form login
     */
    Connection conn=null;
        PreparedStatement state=null;
        ResultSet result=null;
    public login() {
        initComponents();
        conn =dbconnect.dbcon();
        this.setLocationRelativeTo(null); //form to center
    }
    
        public boolean check_employee(String email,String password)
    {
        boolean y=false;
        String id = null,name = null;
        try{
            String quary="SELECT * FROM employees WHERE email='"+ email +"' AND password='"+ password +"'  " ;
            state=conn.prepareStatement(quary);
            result=state.executeQuery();
            y=result.first();
            
            
           
                id=result.getString("empid");
                name=result.getString("name");
                System.out.println(id);
                System.out.println(name);
            
            
            
        }catch(Exception e)
        {
            System.out.println(e);
        }
        name_empf.setText(name);
        id_empf.setText(id);
        return y;
    }
        
        public boolean check_customer(String email,String password)
        {
            String id = null,name = null;
            boolean y=false;
        try{
            String quary="SELECT userid,name FROM customers WHERE email='"+ email +"' AND password='"+ password +"'  " ;
            state=conn.prepareStatement(quary);
            result=state.executeQuery();
            y=result.first();
           
                id=result.getString("userid");
                name=result.getString("name");
                System.out.println(id);
                System.out.println(name);
            
            
            
            
        }catch(Exception e)
        {
            System.out.println(e);
        }
        
        name_cusf.setText(name);
        id_cusf.setText(id);
        return y;
        }



    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        emailf = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jCheckBox1 = new javax.swing.JCheckBox();
        passwordf = new javax.swing.JPasswordField();
        jLabel5 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        Image = new javax.swing.JLabel();
        name_empf = new javax.swing.JLabel();
        id_empf = new javax.swing.JLabel();
        name_cusf = new javax.swing.JLabel();
        id_cusf = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        emailf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailfActionPerformed(evt);
            }
        });
        getContentPane().add(emailf, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 130, 240, 30));

        jButton1.setBackground(new java.awt.Color(204, 204, 255));
        jButton1.setForeground(new java.awt.Color(255, 102, 51));
        jButton1.setText("Login");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 230, 100, -1));

        jCheckBox1.setForeground(new java.awt.Color(255, 255, 255));
        jCheckBox1.setText("Show Password");
        jCheckBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox1ActionPerformed(evt);
            }
        });
        getContentPane().add(jCheckBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 180, -1, -1));
        getContentPane().add(passwordf, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 180, 240, 30));

        jLabel5.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText(" Video Lending System 2.0");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 360, 50));

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("SignUp");
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel2MouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel2MouseEntered(evt);
            }
        });
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 300, -1, -1));

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Do not Hava an Acoount?");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 300, -1, -1));

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Password");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 180, 90, 30));

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Email");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 130, 90, 30));

        Image.setIcon(new javax.swing.ImageIcon(getClass().getResource("/stii/v2/pkg0/fVBHzDf-film-strip-wallpaper.jpg"))); // NOI18N
        getContentPane().add(Image, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 560, 420));

        name_empf.setText("jLabel1");
        getContentPane().add(name_empf, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 50, -1, -1));

        id_empf.setText("jLabel1");
        getContentPane().add(id_empf, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 90, -1, -1));

        name_cusf.setText("jLabel1");
        getContentPane().add(name_cusf, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 50, -1, -1));

        id_cusf.setText("jLabel1");
        getContentPane().add(id_cusf, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 90, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void emailfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emailfActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        
        String un=emailf.getText();
        String ps=passwordf.getText();
        
        if(un.equals("") || (ps.equals("")))
        {
            JOptionPane.showMessageDialog(null,"Please Fill All the Details");
        }
        else
        {
            boolean employee=check_employee(un,ps);
            boolean customer=check_customer(un,ps);

            String name_emp=name_empf.getText();
            String id_emp=id_empf.getText();
            String id_cus=id_cusf.getText();
            String name_cus=name_cusf.getText();
            common form=new common();
           

            if(employee==true)
            {    
                 form.setVisible(true);
                this.hide();
                form.button_hide("employee",name_emp,id_emp);
            }
            else if(customer== true)
            {
                 form.setVisible(true);
                this.hide();
                form.button_hide("customer",name_cus,id_cus);
            }
            else
            {
                JOptionPane.showMessageDialog(null, "Invalid Email & Password");
            }
        }
    
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jCheckBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox1ActionPerformed
        
        if(jCheckBox1.isSelected())
        {
            passwordf.setEchoChar((char)0);
        }
        else
        {
            passwordf.setEchoChar('*');
        }
            
    }//GEN-LAST:event_jCheckBox1ActionPerformed

    private void jLabel2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseEntered
        jLabel2.setForeground(Color.red);
    }//GEN-LAST:event_jLabel2MouseEntered

    private void jLabel2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseExited
        jLabel2.setForeground(Color.WHITE);// TODO add your handling code here:
    }//GEN-LAST:event_jLabel2MouseExited

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
            this.hide();
            signinx form=new signinx();
            form.setVisible(true);
    }//GEN-LAST:event_jLabel2MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Image;
    private javax.swing.JTextField emailf;
    private javax.swing.JLabel id_cusf;
    private javax.swing.JLabel id_empf;
    private javax.swing.JButton jButton1;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel name_cusf;
    private javax.swing.JLabel name_empf;
    private javax.swing.JPasswordField passwordf;
    // End of variables declaration//GEN-END:variables
}
